services:
  postgres:
    image: postgres:16-alpine
    container_name: giftcard_db
    environment:
      POSTGRES_USER: giftcard_user
      POSTGRES_PASSWORD: giftcard_pass
      POSTGRES_DB: giftcard_lifecycle
    ports:
      - "5434:5432"
    volumes:
      - pgdata_giftcard:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U giftcard_user -d giftcard_lifecycle"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata_giftcard:
